# -*- coding: utf-8 -*-
"""analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eo3-_wj3Ryj0nnewbOUPBFZowx_1qRZI
"""

!pip install transformers torch pandas

from transformers import pipeline
import pandas as pd
sentiment = pipeline("sentiment-analysis")
reviews = """the laptop stop quickly.RUN SMOOTHLY.RUN EFFICINTLY.
battery drains fast"""
sentences =reviews.split(".")
pros=[]
cons=[]
for s in sentences:

    s=s.strip()
    if s == "":
      continue
    result=sentiment(s)[0]
    if result["label"] == "POSITIVE":
      pros.append(s)
    elif result["label"] == "NEGATIVE":
      cons.append(s)
pros=pros[:1]
cons=cons[:1]
df=pd.DataFrame({
    "pros":pros,
    "cons":cons
})
df