# -*- coding: utf-8 -*-
"""Copy of textgenrationcode

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14sob_CHQHDrGzykaLx9sKqyeECsEFUgy
"""

!pip install transformers torch

from transformers import pipeline
generator=pipeline(
    "text-generation",
    model="gpt2"
)
prompt="artifical intelligence in hosptial mangement"
result=generator(prompt,max_length=50,num_return_sequences=1)
print("AI generated text:")
print(result[0]['generated_text'])