# -*- coding: utf-8 -*-
"""Time generato.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnvsiXD_ZdeLBOZ-2GUaSR6QNNSwn8jg
"""

import pandas as pd
import random
print("TIMETABLE GENERATOR /n")
subjects_input = input("enter subjects (comma separated ):")
days_input = input("enter days (comma separated):")
periods_per_day = int(input("enter number of periods per day:"))
subjects = [s.strip() for s in subjects_input.split(",") if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]
if len(subjects) == 0 or len(days) == 0 or periods_per_day <= 0:
  print("Invalid input. Please try again.")
else:
  timetable = {}
  for day in days:
    timetable[day] = random.choices(subjects, k=periods_per_day)
  def create_dataframe(timetable):
    df = pd.DataFrame(timetable)
    print("/nTIMETABLE GENERATED SUCCESSFULLY/n")
    display(df)
    df.to_csv("timetable.csv")
    print("/nTIMETABLE SAVED AS TIMETABLE.CSV/n")

